"""Generate per-interface config.yaml from one shared base config plus interface overrides."""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any, Dict, Iterable

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
CONFIG_ROOT = ROOT_DIR / "configs"
GLOBAL_CONFIG_PATH = CONFIG_ROOT / "global.yaml"
INTERFACE_CONFIG_DIR = CONFIG_ROOT / "interfaces"
GENERATED_HEADER = (
    "# Generated by interface_projects/scripts/generate_interface_configs.py\n"
    "# Do not edit this file directly; edit configs/global.yaml or configs/interfaces/*.yaml instead.\n\n"
)


def _read_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"配置文件不存在: {path}")
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict):
        raise ValueError(f"配置文件必须是对象: {path}")
    return payload


def _deep_merge(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    merged = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = copy.deepcopy(value)
    return merged


def discover_interface_names() -> list[str]:
    names: list[str] = []
    for path in sorted(INTERFACE_CONFIG_DIR.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        names.append(path.stem)
    return names


def build_interface_config(interface_name: str) -> Dict[str, Any]:
    shared = _read_yaml(GLOBAL_CONFIG_PATH)
    override = _read_yaml(INTERFACE_CONFIG_DIR / f"{interface_name}.yaml")
    return _deep_merge(shared, override)


def render_interface_config(interface_name: str) -> str:
    payload = build_interface_config(interface_name)
    return GENERATED_HEADER + yaml.safe_dump(payload, allow_unicode=True, sort_keys=False)


def write_interface_config(interface_name: str) -> Path:
    target_dir = ROOT_DIR / interface_name
    if not target_dir.is_dir():
        raise FileNotFoundError(f"接口目录不存在: {target_dir}")
    target_path = target_dir / "config.yaml"
    target_path.write_text(render_interface_config(interface_name), encoding="utf-8")
    return target_path


def write_many(interface_names: Iterable[str]) -> list[Path]:
    written: list[Path] = []
    for interface_name in interface_names:
        written.append(write_interface_config(interface_name))
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 10 个接口各自的 config.yaml")
    parser.add_argument(
        "--interfaces",
        default="all",
        help="逗号分隔的接口目录名，默认 all",
    )
    args = parser.parse_args()

    if args.interfaces.strip().lower() == "all":
        interface_names = discover_interface_names()
    else:
        interface_names = [item.strip() for item in args.interfaces.split(",") if item.strip()]
    if not interface_names:
        raise ValueError("未指定任何接口")

    written = write_many(interface_names)
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
